name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  workflow_run:
    workflows: [Build]
    types:
      - completed
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: jsdaniell/create-json@1.1.2
        with:
          name: "gcloud.json"
          json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/functions/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Build Cloud Functions
        run: | 
            cd functions;
            npm ci;
            npm install --save firebase-tools@latest;
            npm install --save firebase-functions@latest;
      - name: Create SA key
        run: echo `${{ secrets.FIREBASE_SERVICE_ACCOUNT }}` > $HOME/gcloud.json
      - name: Deploy Cloud Functions
        run: export GOOGLE_APPLICATION_CREDENTIALS=gcloud.json && npx firebase-tools deploy --only functions --debug