name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  workflow_run:
    workflows: [Build]
    types:
      - completed
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      
      - name: Get dependencies
        run: | 
            cd functions;
            npm install;
      - name: Deploy to firebase
        uses: w9jds/firebase-action@master
        with:
            args: deploy --only functions
        env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}  