name: Deploy

# Controls when the workflow will run
on: push

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
      - uses: actions/setup-node@v3
        with:
          node-version: 16
  
      - name: Install Dependencies
        run: |
          cd functions
          rm -rf node_modules
          npm ci
  
      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: functions/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('functions/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3

      - name: Restore Cached Node modules
        uses: actions/cache@v3
        with:
          path: functions/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('functions/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies using npm ci
        run: |
          cd functions
          npm ci

      - name: Lint code
        run: |
          cd functions
          npm run lint

  deploy:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Ensure the Node.js version matches your project requirements

      - name: Restore Cached Node modules
        uses: actions/cache@v3
        with:
          path: functions/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('functions/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          cd functions
          npm ci

      - name: Create SA key
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/gcloud.json

      - name: Deploy Cloud Functions
        run: |
          cd functions
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json
          npx firebase-tools deploy --only functions