# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: Change to functions directory
        run: | 
            cd functions;
            npm install;
      - name: Run lint
        run: |
            echo Running lint on src files;
            npx eslint src;

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      
      - name: Change to functions directory
        run: cd functions
      - name: Install dependencies
        run: npm install;
      - name: Deploy to firebase
        uses: w9jds/firebase-action@master
        with:
            args: deploy --only functions
        env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}